### ISSUE TITLE
1.7.2 uses wrong defaults for greylisting

### ISSUE THREAD

**Issue by moisseev** [vstakhov/rmilter#78]
I have no `greylisting` section at all in the configuration file.
After upgrade to 1.7.2 greylisting suddenly starts working, but it shouldn't.
~~~
expire (required): time during which we save a greylisting record
    Default: empty (greylisting disabled)
~~~

**Comment by vstakhov** [comment]
That's the question of default settings sanity. In my opinion, since almost all users want greylisting to work out of the box, it is a good choice to allow them to greylist mail using the default settings. Setting `expire=0` or removing all `servers_grey` and `servers_white` should resolve your issue. But I'll update documentation to reflect that fact that `expire` now has non-zero default.

**Comment by moisseev** [comment]
I didn't mean sanity. It up to you. Rmilter behaves not as documented. So it's "wrong". If you'll update documentation it will be fine.

About what out-of-the-box settings are better. It's questionable. Considering `spamd_greylist` default is `true` you mean "selective" greylisting. I would not enable selective greylisting for new installations in production until statistics trained good enough to avoid undesirable delays. But I see no other reason to disable it by default.
