### ISSUE TITLE
Feature Request: Add header to reflect greylisting

### ISSUE THREAD

**Issue by bax-** [vstakhov/rmilter#80]
I don't know if this would belong to rmilter or rspamd.
But if extended-headers are enabled it would be nice to have a header show that a message / sender had been greylisted.

**Comment by moisseev** [comment]
Or better like the milter-greylist does:
- how long the message has been delayed because of greylisting;
- the message  were not delayed because of whitelisting (e.g. they
are whitelisted in the configuration file);
- the message were not delayed because of auto-whitelisting from a
previously resent and accepted message;

**Comment by vstakhov** [comment]
Could you send me some examples please?

**Comment by moisseev** [comment]
http://hcpnet.free.fr/milter-greylist/README
See the section "19 Things to look at if things get wrong"

**Comment by mnik247** [comment]
And log this info to log file too.
Now I can't understand greylisting info in maillog.

**Comment by mnik247** [comment]
It's correct?
X-Rmilter-Greylist: Greylisted for 304 seconds, whitelisted till 2016-02-12 21:07:53, type: sender, IP, recipients
X-Rmilter-Greylist: Sender IP 0 is whitelisted by configuration

**Comment by mnik247** [comment]
maillog (postfix) not have any this info.

**Comment by mnik247** [comment]
no comment about?
X-Rmilter-Greylist: Greylisted for 304 seconds, whitelisted till 2016-02-12 21:07:53, type: sender, IP, recipients
X-Rmilter-Greylist: Sender IP 0 is whitelisted by configuration
